### ISSUE TITLE
pre-commit support?

### ISSUE THREAD

**Issue by Trim21** [myint/autoflake#61]
add `.pre-commit-hooks.yaml` to project root to support <https://pre-commit.com/>

```yaml

-   id: autoflake
    name: autoflake
    entry: autoflake
    language: python
    'types': [python]
    require_serial: true
```
